### ISSUE TITLE
Funktionalität im Project/Location browser

### ISSUE THREAD

**Issue by bbortt** [bbortt/event-planner#101]
- [x] der Autocomplete hat keine Inzialwerte (leere suche)
  * siehe z.b. beim `project-create.component.ts`
- [x] es fehlt der clientside Filter
- [x] Lokalitäten als Kacheln darstellen
  * siehe `my-projects.component.ts

**Comment by zeroplexer** [comment]
Ist der clientside Filter nicht die `filter` Methode?

` filter(name: string): void {
    if (!name) {
      this.filteredResponsibilities = this.responsibilities;
      return;
    }

    const filterValue = name.toLowerCase();

    if (!this.responsibilities) {
      this.filteredResponsibilities = [] as Responsibility[];
    }

    this.filteredResponsibilities = this.responsibilities.filter(responsibility =>
      responsibility.name!.toLowerCase().includes(filterValue)
    );
  } `

**Comment by bbortt** [comment]
ja, das ist korrekt. nur ist das initiale Value ein leerer String und kann deshalb nicht gefiltert werden..

```ts
filter(name: string): void {
    [...]

    this.filteredResponsibilities = this.responsibilities.filter(responsibility =>
      responsibility.name!.toLowerCase().includes(filterValue)
    );

    // eslint-disable-next-line no-console
    console.log('filter value: ', this.filteredResponsibilities)
  }
```

ergibt:
![image](https://user-images.githubusercontent.com/12272901/101272369-e3659800-378b-11eb-969f-19813c897520.png)

im `project-create.component.ts` fange ich das z.B. ab und query die API dann anders:
```ts
filterUsersByLoginOrEmail(value: string): void {
  if (!value) {
    this.initalLoad();
    return;
  }

  this.userService.findByEmailOrLogin(value).subscribe((users: User[]) => (this.filteredUsers = users));
}

private initalLoad(): void {
  this.userService
    .query({
      page: 0,
      size: 5,
      sort: ['login,asc', 'email,asc'],
    })
    .subscribe((res: HttpResponse<User[]>) => (this.filteredUsers = res.body || []));
}
```

**Comment by bbortt** [comment]
> es fehlt der clientside Filter

nicht nötig, da wir hier eine Kachel-Ansicht verwenden.
cc: @zeroplexer.
