### ISSUE TITLE
Falsche Projekt-Card nach dem Erstellen eines Projektes als normaler User

### ISSUE THREAD

**Issue by Marcarrian** [bbortt/event-planner#64]
Ich bin ein normaler User (kein Super-Admin).
Beim Erstellen eines Projektes erwarte ich die Buttons Drehbuch und Einstellungen.
Ich sehe aber keine Buttons und habe dann keinen Zugriff auf das Projekt.

Nach einem Neustart des Backends funktioniert es wieder und ich sehe die Buttons Drehbuch und Einstellungen.

![image](https://user-images.githubusercontent.com/25194435/98471474-d08f9000-21ec-11eb-86ab-ee9958e4a527.png)

**Comment by bbortt** [comment]
das liegt am caching der user entity. das projekt ist im [`UserDTO`](https://github.com/bbortt/event-planner/blob/canary/src/main/java/io/github/bbortt/event/planner/service/dto/UserDTO.java), `private Map<Long, String> rolePerProject;` hinterlegt. oder eben nicht, weil das ja vor dem erstellen geladen und dann gecached wurde.
frontend mässig ist das die `private userIdentity: Account | null = null;` im [`account.service.ts`](https://github.com/bbortt/event-planner/blob/canary/src/main/webapp/app/core/auth/account.service.ts). diese wird bei einem refresh aber erneut abgefragt.

die [`CacheConfiguration`](https://github.com/bbortt/event-planner/blob/canary/src/main/java/io/github/bbortt/event/planner/config/CacheConfiguration.java) implementier momentan Ehcache, was sowieso nicht skalierbar ist. und dort findet man eben:
```java
createCache(cm, io.github.bbortt.event.planner.repository.UserRepository.USERS_BY_LOGIN_CACHE);
createCache(cm, io.github.bbortt.event.planner.repository.UserRepository.USERS_BY_EMAIL_CACHE);
```

ich schlage vor, die `CacheConfiguration` aufzuräumen, wir haben dort wohl nicht wirklich die übersicht. gewisse dinge wären aber schon gut, zu cachen. auch den `User`-cache finde ich grundsätzlich sinvoll. diese information wird sehr viel abgefragt und verändert sich ausser in diesem speziellen fall fast nie. allerdings müsste er dann hier eben aufgeräumt ("evicted") werden. und im frontend muss kontrolliert werden, dass die `userIdentity` erneut abgefragt wird.

**Comment by bbortt** [comment]
zusammengefasst nach Diskussion: wir entfernen die Caches momentan. beim Drehbuch schauen wir dann, wie sich die Performance verhält.
