### ISSUE TITLE
Meldungen an User sollen keine ID Nummer erhalten

### ISSUE THREAD

**Issue by zeroplexer** [bbortt/event-planner#92]
Der User will den Namen sehen und nicht die ID.

![image](https://user-images.githubusercontent.com/41778593/100544040-744fe700-3253-11eb-9baa-d30a3f51f4ac.png)

**Comment by bbortt** [comment]
@zeroplexer ich glaube, irgendwo hast du das schon angepasst (`{{ id }}` durch `{{ name }}` ersetzt). ist das konsistent über alle tabs umgesetzt? resp. würdest du dies noch anpassen?

**Comment by bbortt** [comment]
resolved in #144.
