### ISSUE TITLE
ngx-autocomplete Bug

### ISSUE THREAD

**Issue by zeroplexer** [bbortt/event-planner#95]
Wenn man das Autocomplete Feld fokussiert und keine Eingabe macht, kann man nicht ein anderes Inputfeld fokussieren.
Bei einer falschen Eingabe erscheinen mehrere Fehlermeldungen
![image](https://user-images.githubusercontent.com/41778593/101019550-707ed600-356d-11eb-86ce-0597bef311f9.png)

**Comment by bbortt** [comment]
auf `canary`?

**Comment by bbortt** [comment]
ok, I receive this too (even on "correct" input):
```
2020-12-03 14:11:23.657  WARN 14404 --- [  XNIO-1 task-2] o.z.problem.spring.common.AdviceTraits   : Method Not Allowed: Request method 'POST' not supported
2020-12-03 14:11:23.662  WARN 14404 --- [  XNIO-1 task-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]
```
will have to look into it. but I cannot reproduce the focus-error.

**Comment by zeroplexer** [comment]
Wenn ich in das Autocomplete Inputfeld nur klicke, kann ich nicht wieder in ein anderes Inputfeld klicken. Ausser wenn ich eine Auswahl fokussiert oder gewählt habe. Bei der Demo funktioniert es tatsächlich.

**Comment by zeroplexer** [comment]
Wollte das Problem mit dem roten invaliden border mit CSS lösen. Jedoch ist der Fehler wohl beim ngx-autocomplete. Die Klasse `ng-invalid` erscheint auf das `<ngx-autocomplete>` und nicht auf das Inputfeld. Das Inputfeld besitzt immer die Klasse `ng-valid`
![image](https://user-images.githubusercontent.com/41778593/101032507-31a34d00-357a-11eb-8b82-015f350d10c9.png)
![image](https://user-images.githubusercontent.com/41778593/101032958-55ff2980-357a-11eb-9cfd-6509e83183ae.png)

**Comment by bbortt** [comment]
der Fehler mit dem roten Balken kannst du so nicht lösen. das ist ein `@angular/forms` Problem. der Autocomplete Komponent besitzt eine eigene kleine Form. es ist nicht möglich, den Validierungs-Status vom Parent ins Children zu kopieren. habe ich im Pull-Request bereits so vermerkt (inkl. Angular Issue) 😄 
beim Lokalitäts-Autocomplete sieht aber auch die Auswahl komisch aus. der Initial-Load schliesst sich sofort wieder. ich schaue auch hier noch rein.
bwt. in Zukunft bitte bei solchen UI sachen den Browser und die URL/die Ansicht in der der Fehler auftritt angeben. 🚀

**Comment by zeroplexer** [comment]
Ups sorry schon wieder vergessen :( 
Der Bug tritt im Chrome auf beim `project-location-update-component` und `project-create-component`
Im Firefox tritt der Bug nicht auf

**Comment by bbortt** [comment]
I cannot reproduce the error on my machine. It's a shame we do not have the `canary` deployment at the time being.

![cannot-reproduce-focus-error](https://user-images.githubusercontent.com/12272901/101135662-64962100-360c-11eb-8a70-db6bf197e14f.gif)

**Comment by bbortt** [comment]
funktioniert nach `npm install` ;)
